# Archivo de configuración para Netlify

[build]
  # Comando de compilación (puede estar vacío para sitios estáticos).
  command = ""

  # Directorio donde se encuentran los archivos públicos (index.html, etc.).
  publish = "."

[functions]
  # Directorio donde Netlify debe buscar las funciones sin servidor.
  directory = "api/"

# [[redirects]] es una regla explícita para el servidor de Netlify.
# Esta regla le dice a Netlify: "Cualquier petición que llegue a /api/lo-que-sea,
# envíala internamente a la función sin servidor llamada lo-que-sea".
# Esto resuelve el problema de mapeo y el error 404.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
